name: Website Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g htmlhint
          npm install -g stylelint stylelint-config-standard
          npm install -g broken-link-checker
          npm install -g pa11y-ci

      - name: Create HTMLHint config
        run: |
          echo '{
            "tagname-lowercase": true,
            "attr-lowercase": true,
            "attr-value-double-quotes": true,
            "doctype-first": true,
            "tag-pair": true,
            "spec-char-escape": true,
            "id-unique": true,
            "src-not-empty": true,
            "attr-no-duplication": true,
            "title-require": true
          }' > .htmlhintrc

      - name: Create Stylelint config
        run: |
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

      - name: HTML Validation
        run: |
          htmlhint "**/*.html"

      - name: CSS Validation
        run: |
          stylelint "**/*.css"

      - name: Check for broken links
        run: |
          blc -r -o --exclude "github.com" .

      - name: Accessibility check
        run: |
          pa11y-ci --sitemap http://localhost:8000 || true
        env:
          CI: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Start local server
        run: |
          python3 -m http.server 8000 &
          sleep 5  # Give the server time to start

      - name: Run accessibility tests
        run: |
          pa11y-ci http://localhost:8000 --sitemap http://localhost:8000/sitemap.xml || true
        env:
          CI: true 